import net from "node:net";
const chunks=[]; const sock=net.connect(2525,"pad.omnidat.cc"); sock.on("data",d=>chunks.push(d));
const send=x=>new Promise(r=>{sock.write(Buffer.from(x,"binary"));setTimeout(r,700);});
await new Promise((r,j)=>{sock.once("connect",r);sock.once("error",j);setTimeout(()=>j(new Error("timeout")),8000);});
await new Promise(r=>setTimeout(r,500));
const grab=()=>{const s=Buffer.concat(chunks).toString("binary");chunks.length=0;return s.split(/\r?\n/).filter(l=>l.trim()).join("\n");};
grab();
await send("RIOT\r"); const r1=grab();
await send("DIRECTORY\r"); const dir=grab();
await send("CALL 020600\r"); grab();
await send("CHANNELS\r"); const ch=grab();
await send("QUIT\r"); await new Promise(r=>setTimeout(r,500)); const back=grab();
console.log("=== RIOT relay (live pad.omnidat.cc) ===\n"+r1);
console.log("=== DIRECTORY ===\n"+dir);
console.log("=== CHANNELS ===\n"+ch);
console.log("=== after QUIT ===\n"+back);
console.log("\nRESULT relay+banner:",/PACKET CLEARING READY/.test(r1),"| guild mirrors:",/020600/.test(dir),"| discord channels:",/general|GENERAL/.test(ch),"| back on PAD:",/PAD>/.test(back));
sock.destroy(); process.exit(0);
